"""add identifier_hash to payment_methods

Revision ID: 2e2a81a7f89c
Revises: 06de9642e8da
Create Date: 2026-05-15 12:49:17.515833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2a81a7f89c'
down_revision: Union[str, Sequence[str], None] = '06de9642e8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('identifier_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_payment_methods_identifier_hash'), 'payment_methods', ['identifier_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_methods_identifier_hash'), table_name='payment_methods')
    op.drop_column('payment_methods', 'identifier_hash')
    # ### end Alembic commands ###
